name: Update Congress Data

on:
  schedule:
    # Runs at 3 AM UTC every day (10 PM EST/7 PM PST)
    - cron: '0 3 * * *'
  # Allows manual trigger
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        # Fetch all history for all branches and tags
        fetch-depth: 0
        # Use the PAT for authentication
        token: ${{ secrets.PAT }}
        # Always get the latest version
        ref: main
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run data fetcher
      env:
        CONGRESS_GOV_API_KEY: ${{ secrets.CONGRESS_GOV_API_KEY }}
      run: python fetch_members.py
    
    - name: Commit and push changes
      env:
        # Use the same PAT for pushing
        PAT: ${{ secrets.PAT }}
      run: |
        # Configure Git
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
        # Set up remote with PAT first
        git remote set-url origin https://${{ github.actor }}:$PAT@github.com/${{ github.repository }}.git
        
        # Add all changes
        git add data/
        
        # Check if there are changes to commit
        if ! git diff --cached --quiet; then
          echo "Data changes detected, committing..."
          git commit -m "Auto-update Congress member data [skip ci]"
          
          # Force push to avoid any merge conflicts
          # This is safe for data-only updates as we want the latest data to take precedence
          echo "Force pushing to avoid merge conflicts..."
          git push --force-with-lease origin HEAD:main
          
          if [ $? -eq 0 ]; then
            echo "Successfully pushed changes"
          else
            echo "Force push failed, trying alternative approach..."
            # Fallback: fetch latest, reset, and try again
            git fetch origin main
            git reset --soft origin/main
            git add data/
            git commit -m "Auto-update Congress member data [skip ci]"
            git push origin HEAD:main
          fi
        else
          echo "No changes to commit"
        fi
