name: Update Congress Data

on:
  schedule:
    # Runs at 3 AM UTC every day (10 PM EST/7 PM PST)
    - cron: '0 3 * * *'
  # Allows manual trigger
  workflow_dispatch:

# Set the permission to write to the repository
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        # Fetch all history for all branches and tags
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run data fetcher
      env:
        CONGRESS_GOV_API_KEY: ${{ secrets.CONGRESS_GOV_API_KEY }}
      run: python fetch_members.py
    
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git config --global --add safe.directory /github/workspace
        
        # Check if there are changes to commit
        git add data/
        if ! git diff --cached --quiet; then
          git commit -m "Auto-update Congress member data [skip ci]"
          git push
        else
          echo "No changes to commit"
        fi
