name: Update Congress Data

on:
  schedule:
    # Runs at 3 AM UTC every day (10 PM EST/7 PM PST)
    - cron: '0 3 * * *'
  # Allows manual trigger
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        # Fetch all history for all branches and tags
        fetch-depth: 0
        # Use the PAT for authentication
        token: ${{ secrets.PAT }}
        # Always get the latest version
        ref: main
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run data fetcher
      env:
        CONGRESS_GOV_API_KEY: ${{ secrets.CONGRESS_GOV_API_KEY }}
      run: python fetch_members.py
    
    - name: Commit and push changes
      env:
        # Use the same PAT for pushing
        PAT: ${{ secrets.PAT }}
      run: |
        # Configure Git
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
        # Add all changes
        git add data/
        
        # Check if there are changes to commit
        if ! git diff --cached --quiet; then
          # Commit changes
          git commit -m "Auto-update Congress member data [skip ci]"
          
          # Set up remote with PAT
          git remote set-url origin https://${{ github.actor }}:$PAT@github.com/${{ github.repository }}.git
          
          # Pull latest changes and handle conflicts
          echo "Pulling latest changes..."
          git fetch origin main
          
          # For data files, we want to use our newly fetched data
          # Try to rebase, if it fails due to data conflicts, resolve by keeping our version
          if git rebase origin/main; then
            echo "Successfully rebased changes"
          else
            echo "Rebase failed, likely due to data file conflicts. Resolving..."
            git rebase --abort
            
            # Merge and resolve conflicts by keeping our data files
            git merge origin/main --no-edit || true
            
            # Check for conflicts and resolve them
            if git status --porcelain | grep -q "^UU\|^AA"; then
              echo "Resolving merge conflicts in data files..."
              # For data files, keep our version (the newly fetched data)
              git status --porcelain | grep "^UU\|^AA" | cut -c4- | while read file; do
                if [[ $file == data/* ]]; then
                  echo "Keeping our version of $file"
                  git add "$file"
                fi
              done
              git commit --no-edit
            fi
          fi
          
          # Push changes with retry logic
          echo "Pushing changes..."
          for i in {1..3}; do
            if git push origin HEAD:main; then
              echo "Successfully pushed changes"
              break
            else
              echo "Push attempt $i failed, retrying..."
              git pull --rebase origin main
              sleep 2
            fi
          done
        else
          echo "No changes to commit"
        fi
